<a href="https://colab.research.google.com/github/Thiwanka570/ML_ModelTraining_Coffie_Sale_Prediction/blob/main/LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd



# Load the data from 'coffee_sale.csv' into a pandas DataFrame.
try:
    df = pd.read_csv('/content/MyDataSet/Salary_dataset.csv')

    # Display the first 5 rows of the DataFrame to verify it loaded correctly.
    display(df.head())

    # Print the DataFrame's information to see data types and non-null counts.
    display(df.info())

except FileNotFoundError:
    print("Could not find 'coffee_sale.csv'. Please ensure the file is in the correct directory.")
    df = None # Set df to None to indicate loading failed

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       30 non-null     int64  
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes


None

In [3]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Unnamed: 0         0.0
YearsExperience    0.0
Salary             0.0
dtype: float64


In [4]:
df.dropna(subset=['Unnamed'], inplace=True)


KeyError: ['Unnamed']

# Task
Train a Linear Regression model on the dataset to predict 'Salary' based on 'YearsExperience', and then use the trained model to predict salaries.

## Data cleaning

### Subtask:
Remove the 'Unnamed: 0' column as it appears to be an index and not a feature.


**Reasoning**:
Remove the 'Unnamed: 0' column from the DataFrame as it is an index column and display the head of the dataframe to verify.



In [5]:
df.drop('Unnamed: 0', axis=1, inplace=True)
display(df.head())

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

from matplotlib import pyplot as plt
_df_0['YearsExperience'].plot(kind='hist', bins=20, title='YearsExperience')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Salary'].plot(kind='hist', bins=20, title='Salary')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='YearsExperience', y='Salary', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['YearsExperience']
  ys = series['Salary']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('YearsExperience', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('YearsExperience')
_ = plt.ylabel('Salary')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['YearsExperience']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'YearsExperience'}, axis=1)
              .sort_values('YearsExperience', ascending=True))
  xs = counted['YearsExperience']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('YearsExperience', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('YearsExperience')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_5['YearsExperience'].plot(kind='line', figsize=(8, 4), title='YearsExperience')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['Salary'].plot(kind='line', figsize=(8, 4), title='Salary')
plt.gca().spines[['top', 'right']].set_visible(False)

## Model selection

### Subtask:
Choose a suitable model for regression, such as Linear Regression.


## Model training

### Subtask:
Train the selected Linear Regression model using 'YearsExperience' as the feature and 'Salary' as the target variable.


**Reasoning**:
Import LinearRegression, instantiate the model, define X and y, and fit the model to the data as per the instructions.



In [6]:
from sklearn.linear_model import LinearRegression

# Instantiate a LinearRegression object.
model = LinearRegression()

# Define the feature variable X and the target variable y.
X = df[['YearsExperience']]  # X must be a 2D array
y = df['Salary']

# Fit the Linear Regression model to the data.
model.fit(X, y)

print("Model training complete.")

Model training complete.


## Prediction

### Subtask:
Use the trained model to predict salaries based on new 'YearsExperience' values.


**Reasoning**:
Define new 'YearsExperience' values and use the trained model to predict salaries for these values.



In [7]:
import numpy as np

# Define new 'YearsExperience' values.
new_years_experience = np.array([1.5, 5.5, 11.0]).reshape(-1, 1) # Reshape for the model's input

# Use the trained model to predict salaries for the new values.
predicted_salaries = model.predict(new_years_experience)

# Display the predicted salaries.
print("Predicted salaries for new YearsExperience values:")
for years, salary in zip(new_years_experience.flatten(), predicted_salaries):
    print(f"Years of Experience: {years}, Predicted Salary: {salary:.2f}")

Predicted salaries for new YearsExperience values:
Years of Experience: 1.5, Predicted Salary: 39023.15
Years of Experience: 5.5, Predicted Salary: 76823.00
Years of Experience: 11.0, Predicted Salary: 128797.79


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


## Summary:

### Data Analysis Key Findings

*   The 'Unnamed: 0' column, likely an index, was removed from the dataset.
*   Linear Regression was selected as the appropriate model due to the observed linear relationship between 'YearsExperience' and 'Salary'.
*   A Linear Regression model was successfully trained using 'YearsExperience' as the feature and 'Salary' as the target variable.
*   The trained model predicted salaries for new 'YearsExperience' values: \$39023.15 for 1.5 years, \$76823.00 for 5.5 years, and \$128797.79 for 11.0 years.

### Insights or Next Steps

*   The trained model can be used to predict salaries for other years of experience within a reasonable range of the training data.
*   Further evaluation of the model's performance (e.g., using R-squared, MSE) would provide a better understanding of its accuracy.
